version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    links:
      - mariadb
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    image: mariadb
    ports:
      - "3306:3306"
